### ISSUE TITLE
Hiding last seen impln

### ISSUE THREAD

**Issue by NandhiniCegc22** [Nandymohan/Selenium#3]
Dear Nandymohan,

It would be greatt if you add the hiding last seen impln feature.

**Comment by NandhiniCegc22** [comment]
``8- Hiding last seen impln

**Comment by Nandymohan** [comment]
thanks.  will add..

**Comment by Nandymohan** [comment]
added..keep supporting.

**Comment by NandhiniCegc22** [comment]
issue number is mismatched..plz update correct one.
